### ISSUE TITLE
itemcreator doesn't work when I create a new item.

### ISSUE THREAD

**Issue by PolsatGraniePL** [SkyCraft78/ItemCreator#5]
```
[14:46:45 INFO]: PolsatGraniePL issued server command: /itemcreator menu
[14:46:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'itemcreator' in plugin ItemCreator v2.3.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2389) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2200) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2181) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class de.tr7zw.changeme.nbtapi.NBTReflectionUtil
        at de.tr7zw.changeme.nbtapi.NBTCompound.setBoolean(NBTCompound.java:385) ~[ItemCreator.jar:?]
        at info.itsthesky.itemcreator.api.properties.simple.SimpleNBTStateProperty.convert(SimpleNBTStateProperty.java:46) ~[ItemCreator.jar:?]
        at info.itsthesky.itemcreator.api.properties.simple.SimpleNBTStateProperty.convert(SimpleNBTStateProperty.java:15) ~[ItemCreator.jar:?]
        at info.itsthesky.itemcreator.api.properties.simple.SimpleNBTProperty.apply(SimpleNBTProperty.java:11) ~[ItemCreator.jar:?]
        at info.itsthesky.itemcreator.core.CustomItem.asItem(CustomItem.java:136) ~[ItemCreator.jar:?]
        at info.itsthesky.itemcreator.core.gui.ItemListGUI.<init>(ItemListGUI.java:93) ~[ItemCreator.jar:?]
        at info.itsthesky.itemcreator.core.CreatorCommand.onCommand(CreatorCommand.java:88) ~[ItemCreator.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more
```

**Comment by ItsTheSky** [comment]
Ic version? Minecraft version?

**Comment by PolsatGraniePL** [comment]
-_-
![image](https://user-images.githubusercontent.com/88681446/174494026-cbcc7c07-0be9-4465-a031-594b8af983e7.png)

**Comment by ItsTheSky** [comment]
Seems this version is not yet supported by ItemCreator. Sorry for the late answer tho!
